AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon Elastic Compute Cloud (EC2) Template
Parameters:
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
      KeyName:  AWS::221024168519 # Replace this with your actual EC2 key pair name
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - sg-07f601e31c15c8a42  # Replace this with your actual security group ID